# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    volumes:
    - ${WEBAPP_STORAGE_HOME}/site:/data/db
    ports:
    - "27017:27017"
      
  catalogapi:
    image: catalogapi
    build:
      context: .
      dockerfile: src/Catalog/Catalog.API/Dockerfile
    ports:
    - "5000:80"
    depends_on:
      - catalogdb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CatalogDatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    volumes:
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
      - ${HOME}/.aspnet/https:/root/.aspnet/https
